INSERT INTO CONTRIBUTOR_TYPE VALUES (0, 'Test');
INSERT INTO BOOK_TYPE VALUES (0, 6, 'Practical Cryptography');
INSERT INTO CONTENT VALUES (0, 'Computers');
INSERT INTO TAG VALUES (0, 'tagovi');
INSERT INTO TAG VALUES (1, 'idu');
INSERT INTO TAG VALUES (2, 'ovde');
INSERT INTO PUBLISHER VALUES (0, 'John Wiley & Sons Incorporated');
INSERT INTO PERSON VALUES(0, 'Niels Ferguson');
INSERT INTO AUTHOR VALUES(0);
INSERT INTO PERSON VALUES(1, 'Bruce Schneier');
INSERT INTO CONTRIBUTOR VALUES (1, 0);
INSERT INTO EDITION VALUES ('Discusses how to choose and use cryptographic primitives, how to implement cryptographic algorithms and systems, how to protect each part of the system and why, and how to reduce system complexity and', '18', 'http://books.google.com/books/content?id=ThVRAAAAMAAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=ThVRAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 410, 1.4, 456, true, PARSEDATETIME('2003', 'yyyy'), 0, 0, 0);
INSERT INTO EDITION_TAGS VALUES(0, 0);
INSERT INTO EDITION_TAGS VALUES(0, 1);
INSERT INTO EDITION_TAGS VALUES(0, 2);
INSERT INTO EDITION_CONTRIBUTORS VALUES(0, 1);
INSERT INTO EDITION_CONTENT VALUES(0, 0);
INSERT INTO BOOK_TYPE VALUES (1, 28, 'Applied Cryptography');
INSERT INTO PUBLISHER VALUES (1, 'John Wiley & Sons');
INSERT INTO EDITION VALUES ('"This special Anniversary Edition celebrates 20 years for the most definitive reference on cryptography ever published." -- Book jacket. New introduction by the author.', '19', 'http://books.google.com/books/content?id=VjC9BgAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=VjC9BgAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 784, 1.9, 333, true, PARSEDATETIME('2015', 'yyyy'), 1, 1, 1);
INSERT INTO EDITION_TAGS VALUES(1, 0);
INSERT INTO EDITION_TAGS VALUES(1, 1);
INSERT INTO EDITION_TAGS VALUES(1, 2);
INSERT INTO EDITION_CONTENT VALUES(1, 0);
INSERT INTO BOOK_TYPE VALUES (2, 28, 'Cryptography For Dummies');
INSERT INTO PERSON VALUES(2, 'Chey Cobb');
INSERT INTO AUTHOR VALUES(2);
INSERT INTO EDITION VALUES ('Cryptography is the most effective way to achieve data securityand is essential to e-commerce activities such as online shopping,stock trading, and banking This invaluable introduction to the basics o', '22', 'http://books.google.com/books/content?id=b3pQDh7j5ogC&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=b3pQDh7j5ogC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 324, 5.0, 393, false, PARSEDATETIME('2004', 'yyyy'), 2, 2, 1);
INSERT INTO EDITION_TAGS VALUES(2, 0);
INSERT INTO EDITION_TAGS VALUES(2, 1);
INSERT INTO EDITION_TAGS VALUES(2, 2);
INSERT INTO EDITION_CONTENT VALUES(2, 0);
INSERT INTO BOOK_TYPE VALUES (3, 8, 'Cryptography: A Very Short Introduction');
INSERT INTO PUBLISHER VALUES (2, 'Oxford Paperbacks');
INSERT INTO PERSON VALUES(3, 'Fred Piper');
INSERT INTO AUTHOR VALUES(3);
INSERT INTO PERSON VALUES(4, 'Sean Murphy');
INSERT INTO CONTRIBUTOR VALUES (4, 0);
INSERT INTO EDITION VALUES ('This Very Short Introduction provides a clear and informative introduction to the science of codebreaking, and its explosive impact on modern society. Taking the reader through the actual processes of', '20', 'http://books.google.com/books/content?id=HvR0DgAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=HvR0DgAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 142, 3.4, 306, true, PARSEDATETIME('2002', 'yyyy'), 3, 3, 2);
INSERT INTO EDITION_TAGS VALUES(3, 0);
INSERT INTO EDITION_TAGS VALUES(3, 1);
INSERT INTO EDITION_TAGS VALUES(3, 2);
INSERT INTO EDITION_CONTRIBUTORS VALUES(3, 4);
INSERT INTO EDITION_CONTENT VALUES(3, 0);
INSERT INTO BOOK_TYPE VALUES (4, 57, 'Understanding Cryptography');
INSERT INTO PUBLISHER VALUES (3, 'Springer Science & Business Media');
INSERT INTO PERSON VALUES(5, 'Christof Paar');
INSERT INTO AUTHOR VALUES(5);
INSERT INTO PERSON VALUES(6, 'Jan Pelzl');
INSERT INTO CONTRIBUTOR VALUES (6, 0);
INSERT INTO EDITION VALUES ('Cryptography is now ubiquitous – moving beyond the traditional environments, such as government communications and banking systems, we see cryptographic techniques realized in Web browsers, e-mail pro', '21', 'http://books.google.com/books/content?id=f24wFELSzkoC&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=f24wFELSzkoC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 372, 1.5, 42, true, PARSEDATETIME('2009', 'yyyy'), 4, 5, 3);
INSERT INTO EDITION_TAGS VALUES(4, 0);
INSERT INTO EDITION_TAGS VALUES(4, 1);
INSERT INTO EDITION_TAGS VALUES(4, 2);
INSERT INTO EDITION_CONTRIBUTORS VALUES(4, 6);
INSERT INTO EDITION_CONTENT VALUES(4, 0);
INSERT INTO BOOK_TYPE VALUES (5, 30, 'Serious Cryptography');
INSERT INTO PUBLISHER VALUES (4, 'None');
INSERT INTO PERSON VALUES(7, 'Jean-Philippe Aumasson');
INSERT INTO AUTHOR VALUES(7);
INSERT INTO EDITION VALUES ('Serious Cryptography is the much anticipated review of modern cryptography by cryptographer JP Aumasson. This is a book for readers who want to understand how cryptography works in today''s world. The', '19', 'http://books.google.com/books/content?id=W1v6DwAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=W1v6DwAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 312, 4.4, 309, true, PARSEDATETIME('2017', 'yyyy'), 5, 7, 4);
INSERT INTO EDITION_TAGS VALUES(5, 0);
INSERT INTO EDITION_TAGS VALUES(5, 1);
INSERT INTO EDITION_TAGS VALUES(5, 2);
INSERT INTO EDITION_CONTENT VALUES(5, 0);
INSERT INTO BOOK_TYPE VALUES (6, 37, 'Introduction to Cryptography');
INSERT INTO PERSON VALUES(8, 'Hans Delfs');
INSERT INTO AUTHOR VALUES(8);
INSERT INTO PERSON VALUES(9, 'Helmut Knebl');
INSERT INTO CONTRIBUTOR VALUES (9, 0);
INSERT INTO EDITION VALUES ('The opening section of this book covers key concepts of cryptography, from encryption and digital signatures to cryptographic protocols. Essential techniques are demonstrated in protocols for key exch', '19', 'http://books.google.com/books/content?id=Nnvhz_VqAS4C&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=Nnvhz_VqAS4C&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 367, 4.2, 435, true, PARSEDATETIME('2007', 'yyyy'), 6, 8, 3);
INSERT INTO EDITION_TAGS VALUES(6, 0);
INSERT INTO EDITION_TAGS VALUES(6, 1);
INSERT INTO EDITION_TAGS VALUES(6, 2);
INSERT INTO EDITION_CONTRIBUTORS VALUES(6, 9);
INSERT INTO EDITION_CONTENT VALUES(6, 0);
INSERT INTO BOOK_TYPE VALUES (7, 43, 'Everyday Cryptography');
INSERT INTO PUBLISHER VALUES (5, 'Oxford University Press');
INSERT INTO PERSON VALUES(10, 'Keith Martin');
INSERT INTO AUTHOR VALUES(10);
INSERT INTO EDITION VALUES ('Cryptography is a vital technology that underpins the security of information in computer networks. This book presents a comprehensive introduction to the role that cryptography plays in providing inf', '18', 'http://books.google.com/books/content?id=TS3VDgAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=TS3VDgAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 672, 2.0, 408, true, PARSEDATETIME('2017', 'yyyy'), 7, 10, 5);
INSERT INTO EDITION_TAGS VALUES(7, 0);
INSERT INTO EDITION_TAGS VALUES(7, 1);
INSERT INTO EDITION_TAGS VALUES(7, 2);
INSERT INTO EDITION_CONTENT VALUES(7, 0);
INSERT INTO BOOK_TYPE VALUES (8, 48, 'Introduction to Modern Cryptography, Second Edition');
INSERT INTO PUBLISHER VALUES (6, 'CRC Press');
INSERT INTO PERSON VALUES(11, 'Jonathan Katz');
INSERT INTO AUTHOR VALUES(11);
INSERT INTO PERSON VALUES(12, 'Yehuda Lindell');
INSERT INTO CONTRIBUTOR VALUES (12, 0);
INSERT INTO EDITION VALUES ('Cryptography is ubiquitous and plays a key role in ensuring data secrecy and integrity as well as in securing computer systems more broadly. Introduction to Modern Cryptography provides a rigorous yet', '19', 'http://books.google.com/books/content?id=OWZYBQAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=OWZYBQAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 603, 4.6, 400, true, PARSEDATETIME('2014', 'yyyy'), 8, 11, 6);
INSERT INTO EDITION_TAGS VALUES(8, 0);
INSERT INTO EDITION_TAGS VALUES(8, 1);
INSERT INTO EDITION_TAGS VALUES(8, 2);
INSERT INTO EDITION_CONTRIBUTORS VALUES(8, 12);
INSERT INTO EDITION_CONTENT VALUES(8, 0);
INSERT INTO BOOK_TYPE VALUES (9, 53, 'Java Performance');
INSERT INTO PUBLISHER VALUES (7, 'Prentice Hall');
INSERT INTO PERSON VALUES(13, 'Charlie Hunt');
INSERT INTO AUTHOR VALUES(13);
INSERT INTO PERSON VALUES(14, 'Binu John');
INSERT INTO CONTRIBUTOR VALUES (14, 0);
INSERT INTO EDITION VALUES ('The ONLY complete, up-to-date guide to all aspects of Java performance • •The first one-stop guide to identifying, isolating, and fixing Java performance issues on multicore and multiprocessor process', '19', 'http://books.google.com/books/content?id=7mktLCw0E2IC&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=7mktLCw0E2IC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 693, 3.1, 307, true, PARSEDATETIME('2012', 'yyyy'), 9, 13, 7);
INSERT INTO EDITION_TAGS VALUES(9, 0);
INSERT INTO EDITION_TAGS VALUES(9, 1);
INSERT INTO EDITION_TAGS VALUES(9, 2);
INSERT INTO EDITION_CONTRIBUTORS VALUES(9, 14);
INSERT INTO EDITION_CONTENT VALUES(9, 0);
INSERT INTO BOOK_TYPE VALUES (10, 38, 'Osnove Java programiranja');
INSERT INTO BOOK_TYPE VALUES (11, 38, 'Java Generics and Collections');
INSERT INTO PUBLISHER VALUES (8, '"O''Reilly Media, Inc."');
INSERT INTO PERSON VALUES(15, 'Maurice Naftalin');
INSERT INTO AUTHOR VALUES(15);
INSERT INTO PERSON VALUES(16, 'Philip Wadler');
INSERT INTO CONTRIBUTOR VALUES (16, 0);
INSERT INTO EDITION VALUES ('This book, written by one of the designers of generics, is a thorough explanation of how to use generics, and particularly, the effect this facility has on the way developers use collections.', '20', 'http://books.google.com/books/content?id=VUSbAgAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=VUSbAgAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 273, 3.5, 320, true, PARSEDATETIME('2007', 'yyyy'), 11, 15, 8);
INSERT INTO EDITION_TAGS VALUES(11, 0);
INSERT INTO EDITION_TAGS VALUES(11, 1);
INSERT INTO EDITION_TAGS VALUES(11, 2);
INSERT INTO EDITION_CONTRIBUTORS VALUES(11, 16);
INSERT INTO EDITION_CONTENT VALUES(11, 0);
INSERT INTO BOOK_TYPE VALUES (12, 42, 'TCP/IP Sockets in Java');
INSERT INTO PUBLISHER VALUES (9, 'Morgan Kaufmann');
INSERT INTO PERSON VALUES(17, 'Kenneth L. Calvert');
INSERT INTO AUTHOR VALUES(17);
INSERT INTO PERSON VALUES(18, 'Michael J. Donahoo');
INSERT INTO CONTRIBUTOR VALUES (18, 0);
INSERT INTO EDITION VALUES ('The networking capabilities of the Java platform have been extended considerably since the first edition of the book. This new edition covers version 1.5-1.7, the most current iterations, as well as m', '20', 'http://books.google.com/books/content?id=lfHo7uMk7r4C&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=lfHo7uMk7r4C&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'en', 192, 4.4, 29, true, PARSEDATETIME('2011', 'yyyy'), 12, 17, 9);
INSERT INTO EDITION_TAGS VALUES(12, 0);
INSERT INTO EDITION_TAGS VALUES(12, 1);
INSERT INTO EDITION_TAGS VALUES(12, 2);
INSERT INTO EDITION_CONTRIBUTORS VALUES(12, 18);
INSERT INTO EDITION_CONTENT VALUES(12, 0);
INSERT INTO BOOK_TYPE VALUES (13, 56, 'Killer Game Programming in Java');
INSERT INTO PERSON VALUES(19, 'Andrew Davison');
INSERT INTO AUTHOR VALUES(19);
INSERT INTO EDITION VALUES ('Although the number of commercial Java games is still small compared to those written in C or C++, the market is expanding rapidly. Recent updates to Java make it faster and easier to create powerful ', '22', 'http://books.google.com/books/content?id=dOz-UK8Fl_UC&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=dOz-UK8Fl_UC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 998, 1.9, 438, true, PARSEDATETIME('2005', 'yyyy'), 13, 19, 8);
INSERT INTO EDITION_TAGS VALUES(13, 0);
INSERT INTO EDITION_TAGS VALUES(13, 1);
INSERT INTO EDITION_TAGS VALUES(13, 2);
INSERT INTO EDITION_CONTENT VALUES(13, 0);
INSERT INTO BOOK_TYPE VALUES (14, 38, 'Ecology of Java & Bali');
INSERT INTO CONTENT VALUES (1, 'Nature');
INSERT INTO PUBLISHER VALUES (10, 'Tuttle Publishing');
INSERT INTO PERSON VALUES(20, 'Anthony J. Whitten');
INSERT INTO AUTHOR VALUES(20);
INSERT INTO PERSON VALUES(21, 'Roehayat Emon Soeriaatmadja');
INSERT INTO CONTRIBUTOR VALUES (21, 0);
INSERT INTO EDITION VALUES ('The Ecology of Java and Bali is a comprehensive ecological survey of two of the most ecologically diverse islands in the Pacific. It also contains the results of original research, interviews and pers', '22', 'http://books.google.com/books/content?id=aP_PAgAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=aP_PAgAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 1004, 1.4, 407, true, PARSEDATETIME('2013', 'yyyy'), 14, 20, 10);
INSERT INTO EDITION_TAGS VALUES(14, 0);
INSERT INTO EDITION_TAGS VALUES(14, 1);
INSERT INTO EDITION_TAGS VALUES(14, 2);
INSERT INTO EDITION_CONTRIBUTORS VALUES(14, 21);
INSERT INTO EDITION_CONTENT VALUES(14, 1);
INSERT INTO BOOK_TYPE VALUES (15, 55, 'OCA / OCP Java SE 8 Programmer Practice Tests');
INSERT INTO PERSON VALUES(22, 'Scott Selikoff');
INSERT INTO AUTHOR VALUES(22);
INSERT INTO PERSON VALUES(23, 'Jeanne Boyarsky');
INSERT INTO CONTRIBUTOR VALUES (23, 0);
INSERT INTO EDITION VALUES ('Test your knowledge and prepare for the OCA/OCP exams OCA/OCP Java SE 8 Programmer Practice Tests complements the Sybex OCA: Oracle Certified Associate Java SE 8 Programmer I Certification Study Guide', '21', 'http://books.google.com/books/content?id=CR9IDgAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=CR9IDgAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 600, 3.5, 221, true, PARSEDATETIME('2017', 'yyyy'), 15, 22, 1);
INSERT INTO EDITION_TAGS VALUES(15, 0);
INSERT INTO EDITION_TAGS VALUES(15, 1);
INSERT INTO EDITION_TAGS VALUES(15, 2);
INSERT INTO EDITION_CONTRIBUTORS VALUES(15, 23);
INSERT INTO EDITION_CONTENT VALUES(15, 0);
INSERT INTO BOOK_TYPE VALUES (16, 15, 'Thinking in Java');
INSERT INTO PUBLISHER VALUES (11, 'Prentice Hall Professional');
INSERT INTO PERSON VALUES(24, 'Bruce Eckel');
INSERT INTO AUTHOR VALUES(24);
INSERT INTO EDITION VALUES ('An overview of the programming language''s fundamentals covers syntax, initialization, implementation, classes, error handling, objects, applets, multiple threads, projects, and network programming.', '20', 'http://books.google.com/books/content?id=Ql6QgWf6i7cC&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=Ql6QgWf6i7cC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 1119, 4.1, 426, true, PARSEDATETIME('2003', 'yyyy'), 16, 24, 11);
INSERT INTO EDITION_TAGS VALUES(16, 0);
INSERT INTO EDITION_TAGS VALUES(16, 1);
INSERT INTO EDITION_TAGS VALUES(16, 2);
INSERT INTO EDITION_CONTENT VALUES(16, 0);
INSERT INTO BOOK_TYPE VALUES (17, 31, 'Effective Java');
INSERT INTO PUBLISHER VALUES (12, 'Test 览百分比');
INSERT INTO PERSON VALUES(25, 'Joshua Bloch');
INSERT INTO AUTHOR VALUES(25);
INSERT INTO EDITION VALUES ('Are you looking for a deeper understanding of the Java™ programming language so that you can write code that is clearer, more correct, more robust, and more reusable? Look no further! Effective Java™,', '19', 'http://books.google.com/books/content?id=Ft8t0S4VjmwC&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=Ft8t0S4VjmwC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 368, 1.0, 199, false, PARSEDATETIME('2008', 'yyyy'), 17, 25, 12);
INSERT INTO EDITION_TAGS VALUES(17, 0);
INSERT INTO EDITION_TAGS VALUES(17, 1);
INSERT INTO EDITION_TAGS VALUES(17, 2);
INSERT INTO EDITION_CONTENT VALUES(17, 0);
INSERT INTO BOOK_TYPE VALUES (18, 34, 'Black Hat Python');
INSERT INTO PUBLISHER VALUES (13, 'No Starch Press');
INSERT INTO PERSON VALUES(26, 'Justin Seitz');
INSERT INTO AUTHOR VALUES(26);
INSERT INTO EDITION VALUES ('In Black Hat Python, the latest from Justin Seitz (author of the best-selling Gray Hat Python), you’ll explore the darker side of Python’s capabilities—writing network sniffers, manipulating packets, ', '19', 'http://books.google.com/books/content?id=9MS9BQAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=9MS9BQAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 192, 3.9, 130, true, PARSEDATETIME('2014', 'yyyy'), 18, 26, 13);
INSERT INTO EDITION_TAGS VALUES(18, 0);
INSERT INTO EDITION_TAGS VALUES(18, 1);
INSERT INTO EDITION_TAGS VALUES(18, 2);
INSERT INTO EDITION_CONTENT VALUES(18, 0);
INSERT INTO BOOK_TYPE VALUES (19, 47, 'Head First Python');
INSERT INTO PERSON VALUES(27, 'Paul Barry');
INSERT INTO AUTHOR VALUES(27);
INSERT INTO EDITION VALUES ('A guide to the programming language describes how to build Python-enabled Web servers and applications, write mobile apps on the Android platform, develop sophisticated games, build GUI-based programs', '22', 'http://books.google.com/books/content?id=ENIVBdZIJ6cC&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=ENIVBdZIJ6cC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 457, 4.1, 498, true, PARSEDATETIME('2010', 'yyyy'), 19, 27, 8);
INSERT INTO EDITION_TAGS VALUES(19, 0);
INSERT INTO EDITION_TAGS VALUES(19, 1);
INSERT INTO EDITION_TAGS VALUES(19, 2);
INSERT INTO EDITION_CONTENT VALUES(19, 0);
INSERT INTO BOOK_TYPE VALUES (20, 44, 'Python Programming');
INSERT INTO PUBLISHER VALUES (14, 'Franklin, Beedle & Associates, Inc.');
INSERT INTO PERSON VALUES(28, 'John M. Zelle');
INSERT INTO AUTHOR VALUES(28);
INSERT INTO EDITION VALUES ('This book is suitable for use in a university-level first course in computing (CS1), as well as the increasingly popular course known as CS0. It is difficult for many students to master basic concepts', '22', 'http://books.google.com/books/content?id=aJQILlLxRmAC&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=aJQILlLxRmAC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 517, 4.1, 288, true, PARSEDATETIME('2004', 'yyyy'), 20, 28, 14);
INSERT INTO EDITION_TAGS VALUES(20, 0);
INSERT INTO EDITION_TAGS VALUES(20, 1);
INSERT INTO EDITION_TAGS VALUES(20, 2);
INSERT INTO EDITION_CONTENT VALUES(20, 0);
INSERT INTO BOOK_TYPE VALUES (21, 44, 'Python Playground');
INSERT INTO PERSON VALUES(29, 'Mahesh Venkitachalam');
INSERT INTO AUTHOR VALUES(29);
INSERT INTO EDITION VALUES ('Python is a powerful programming language that’s easy to learn and fun to play with. But once you’ve gotten a handle on the basics, what do you do next? Python Playground is a collection of imaginativ', '22', 'http://books.google.com/books/content?id=YRHSCgAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=YRHSCgAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 352, 2.9, 61, true, PARSEDATETIME('2015', 'yyyy'), 21, 29, 13);
INSERT INTO EDITION_TAGS VALUES(21, 0);
INSERT INTO EDITION_TAGS VALUES(21, 1);
INSERT INTO EDITION_TAGS VALUES(21, 2);
INSERT INTO EDITION_CONTENT VALUES(21, 0);
INSERT INTO BOOK_TYPE VALUES (22, 36, 'Mission Python');
INSERT INTO CONTENT VALUES (2, 'COMPUTERS');
INSERT INTO PERSON VALUES(30, 'Sean McManus');
INSERT INTO AUTHOR VALUES(30);
INSERT INTO EDITION VALUES ('Launch into coding with Mission: Python, a space-themed guide to building a complete computer game in Python. As you work through the book, you''ll build exercises and mini-projects, like making a spa', '22', 'http://books.google.com/books/content?id=e1v6DwAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=e1v6DwAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 280, 2.6, 124, false, PARSEDATETIME('2018', 'yyyy'), 22, 30, 4);
INSERT INTO EDITION_TAGS VALUES(22, 0);
INSERT INTO EDITION_TAGS VALUES(22, 1);
INSERT INTO EDITION_TAGS VALUES(22, 2);
INSERT INTO EDITION_CONTENT VALUES(22, 2);
INSERT INTO BOOK_TYPE VALUES (23, 14, 'Python Essential Reference');
INSERT INTO PUBLISHER VALUES (15, 'Addison-Wesley Professional');
INSERT INTO PERSON VALUES(31, 'David M. Beazley');
INSERT INTO AUTHOR VALUES(31);
INSERT INTO EDITION VALUES ('Presents a guide to the features and library modules of the Python programming language.', '21', 'http://books.google.com/books/content?id=Chr1NDlUcI8C&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=Chr1NDlUcI8C&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 717, 3.8, 398, false, PARSEDATETIME('2009', 'yyyy'), 23, 31, 15);
INSERT INTO EDITION_TAGS VALUES(23, 0);
INSERT INTO EDITION_TAGS VALUES(23, 1);
INSERT INTO EDITION_TAGS VALUES(23, 2);
INSERT INTO EDITION_CONTENT VALUES(23, 0);
INSERT INTO BOOK_TYPE VALUES (24, 47, 'Learning Python with Raspberry Pi');
INSERT INTO PERSON VALUES(32, 'Alex Bradbury');
INSERT INTO AUTHOR VALUES(32);
INSERT INTO PERSON VALUES(33, 'Russel Winder');
INSERT INTO CONTRIBUTOR VALUES (33, 0);
INSERT INTO PERSON VALUES(34, 'Ben Everard');
INSERT INTO CONTRIBUTOR VALUES (34, 0);
INSERT INTO EDITION VALUES ('Explains how to leverage the revolutionary Raspberry Pi computer in order to learn the versatile Python programming language. Original.', '22', 'http://books.google.com/books/content?id=BP_WAgAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=BP_WAgAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 286, 2.2, 368, false, PARSEDATETIME('2014', 'yyyy'), 24, 32, 1);
INSERT INTO EDITION_TAGS VALUES(24, 0);
INSERT INTO EDITION_TAGS VALUES(24, 1);
INSERT INTO EDITION_TAGS VALUES(24, 2);
INSERT INTO EDITION_CONTRIBUTORS VALUES(24, 33);
INSERT INTO EDITION_CONTRIBUTORS VALUES(24, 34);
INSERT INTO EDITION_CONTENT VALUES(24, 0);
INSERT INTO BOOK_TYPE VALUES (25, 31, 'Mastering Python Design Patterns');
INSERT INTO PUBLISHER VALUES (16, 'Packt Publishing Ltd');
INSERT INTO PERSON VALUES(35, 'Kamon Ayeva');
INSERT INTO AUTHOR VALUES(35);
INSERT INTO PERSON VALUES(36, 'Sakis Kasampalis');
INSERT INTO CONTRIBUTOR VALUES (36, 0);
INSERT INTO EDITION VALUES ('Python is an object-oriented, scripting language that is used in wide range of categories. In software engineering, a design pattern is a recommended solution to a software design problem. Although no', '18', 'http://books.google.com/books/content?id=PshsDwAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=PshsDwAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 248, 4.9, 137, true, PARSEDATETIME('2018', 'yyyy'), 25, 35, 16);
INSERT INTO EDITION_TAGS VALUES(25, 0);
INSERT INTO EDITION_TAGS VALUES(25, 1);
INSERT INTO EDITION_TAGS VALUES(25, 2);
INSERT INTO EDITION_CONTRIBUTORS VALUES(25, 36);
INSERT INTO EDITION_CONTENT VALUES(25, 0);