INSERT INTO TAG VALUES(0, 'cryptography');
INSERT INTO TAG VALUES(1, 'security');
INSERT INTO TAG VALUES(2, 'computers');
INSERT INTO TAG VALUES(3, 'communications');
INSERT INTO TAG VALUES(4, 'programming');
INSERT INTO TAG VALUES(5, 'python');
INSERT INTO TAG VALUES(6, 'c++');
INSERT INTO GENRE VALUES(0, 'Computers');
INSERT INTO GENRE VALUES(1, 'Business & Economics');
INSERT INTO GENRE VALUES(2, 'Mathematics');
INSERT INTO CONTRIBUTOR VALUES(0, 'Bruce Schneier');
INSERT INTO CONTRIBUTOR VALUES(1, 'Chey Cobb');
INSERT INTO CONTRIBUTOR VALUES(2, 'Fred Piper');
INSERT INTO CONTRIBUTOR VALUES(3, 'Sean Murphy');
INSERT INTO CONTRIBUTOR VALUES(4, 'Hans Delfs');
INSERT INTO CONTRIBUTOR VALUES(5, 'Helmut Knebl');
INSERT INTO CONTRIBUTOR VALUES(6, 'Keith Martin');
INSERT INTO CONTRIBUTOR VALUES(7, 'Christof Paar');
INSERT INTO CONTRIBUTOR VALUES(8, 'Jan Pelzl');
INSERT INTO CONTRIBUTOR VALUES(9, 'Joe Kilian');
INSERT INTO CONTRIBUTOR VALUES(10, 'Justin Seitz');
INSERT INTO CONTRIBUTOR VALUES(11, 'Alex Martelli');
INSERT INTO CONTRIBUTOR VALUES(12, 'Al Sweigart');
INSERT INTO CONTRIBUTOR VALUES(13, 'Mahesh Venkitachalam');
INSERT INTO CONTRIBUTOR VALUES(14, 'David M. Beazley');
INSERT INTO CONTRIBUTOR VALUES(15, 'John M. Zelle');
INSERT INTO CONTRIBUTOR VALUES(16, 'Alex Bradbury');
INSERT INTO CONTRIBUTOR VALUES(17, 'Russel Winder');
INSERT INTO CONTRIBUTOR VALUES(18, 'Ben Everard');
INSERT INTO CONTRIBUTOR VALUES(19, 'Nicolai M. Josuttis');
INSERT INTO CONTRIBUTOR VALUES(20, 'Steve Oualline');
INSERT INTO CONTRIBUTOR VALUES(21, 'Mike Hendrickson');
INSERT INTO CONTRIBUTOR VALUES(22, 'Andrew Koenig');
INSERT INTO CONTRIBUTOR VALUES(23, 'Barbara E. Moo');
INSERT INTO CONTRIBUTOR VALUES(24, 'Stephen R. Davis');
INSERT INTO CONTRIBUTOR VALUES(25, 'Marc Gregoire');
INSERT INTO CONTRIBUTOR VALUES(26, 'John Lakos');
INSERT INTO CONTRIBUTOR VALUES(27, 'Randall L. Eubank');
INSERT INTO CONTRIBUTOR VALUES(28, 'Ana Kupresanin');
INSERT INTO CONTRIBUTOR VALUES(29, 'Ray Lischner');
INSERT INTO CONTRIBUTOR VALUES(30, 'Cay S. Horstmann');
INSERT INTO CONTRIBUTION VALUES(0, 'author', 0);
INSERT INTO CONTRIBUTION VALUES(1, 'author', 1);
INSERT INTO CONTRIBUTION VALUES(2, 'author', 2);
INSERT INTO CONTRIBUTION VALUES(3, 'author', 3);
INSERT INTO CONTRIBUTION VALUES(4, 'author', 4);
INSERT INTO CONTRIBUTION VALUES(5, 'author', 5);
INSERT INTO CONTRIBUTION VALUES(6, 'author', 6);
INSERT INTO CONTRIBUTION VALUES(7, 'author', 7);
INSERT INTO CONTRIBUTION VALUES(8, 'author', 8);
INSERT INTO CONTRIBUTION VALUES(9, 'author', 9);
INSERT INTO CONTRIBUTION VALUES(10, 'author', 10);
INSERT INTO CONTRIBUTION VALUES(11, 'author', 11);
INSERT INTO CONTRIBUTION VALUES(12, 'author', 12);
INSERT INTO CONTRIBUTION VALUES(13, 'author', 13);
INSERT INTO CONTRIBUTION VALUES(14, 'author', 14);
INSERT INTO CONTRIBUTION VALUES(15, 'author', 15);
INSERT INTO CONTRIBUTION VALUES(16, 'author', 16);
INSERT INTO CONTRIBUTION VALUES(17, 'author', 17);
INSERT INTO CONTRIBUTION VALUES(18, 'author', 18);
INSERT INTO CONTRIBUTION VALUES(19, 'author', 19);
INSERT INTO CONTRIBUTION VALUES(20, 'author', 20);
INSERT INTO CONTRIBUTION VALUES(21, 'author', 21);
INSERT INTO CONTRIBUTION VALUES(22, 'author', 22);
INSERT INTO CONTRIBUTION VALUES(23, 'author', 23);
INSERT INTO CONTRIBUTION VALUES(24, 'author', 24);
INSERT INTO CONTRIBUTION VALUES(25, 'author', 25);
INSERT INTO CONTRIBUTION VALUES(26, 'author', 26);
INSERT INTO CONTRIBUTION VALUES(27, 'author', 27);
INSERT INTO CONTRIBUTION VALUES(28, 'author', 28);
INSERT INTO CONTRIBUTION VALUES(29, 'author', 29);
INSERT INTO CONTRIBUTION VALUES(30, 'author', 30);
INSERT INTO PUBLISHER VALUES(0, 'John Wiley & Sons');
INSERT INTO PUBLISHER VALUES(1, 'Oxford Paperbacks');
INSERT INTO PUBLISHER VALUES(2, 'Springer Science & Business Media');
INSERT INTO PUBLISHER VALUES(3, 'Oxford University Press');
INSERT INTO PUBLISHER VALUES(4, 'No Starch Press');
INSERT INTO PUBLISHER VALUES(5, '"O''Reilly Media, Inc."');
INSERT INTO PUBLISHER VALUES(6, 'Addison-Wesley Professional');
INSERT INTO PUBLISHER VALUES(7, 'Franklin, Beedle & Associates, Inc.');
INSERT INTO PUBLISHER VALUES(8, 'CRC Press');
INSERT INTO PUBLISHER VALUES(9, 'O''Reilly Media');
INSERT INTO BOOK_TITLE VALUES(0, 'Applied Cryptography');
INSERT INTO EDITION VALUES(0, 6, '"This special Anniversary Edition celebrates 20 years for the most definitive reference on cryptography ever published." -- Book jacket. New introduction by the author.', '18', 'http://books.google.com/books/content?id=VjC9BgAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=VjC9BgAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 784, 3.0, 502, false, PARSEDATETIME('2015', 'yyyy'), 0, 0);INSERT INTO BOOK_TITLE_EDITIONS VALUES(0, 0);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(0, 0);
INSERT INTO EDITION_CONTENT VALUES(0, 0);
INSERT INTO EDITION_TAGS VALUES(0, 0);
INSERT INTO EDITION_TAGS VALUES(0, 1);
INSERT INTO EDITION_TAGS VALUES(0, 2);
INSERT INTO EDITION_TAGS VALUES(0, 3);
INSERT INTO BOOK_TITLE VALUES(1, 'Cryptography For Dummies');
INSERT INTO EDITION VALUES(1, 45, 'Cryptography is the most effective way to achieve data securityand is essential to e-commerce activities such as online shopping,stock trading, and banking This invaluable introduction to the basics of encryption coverseverything from the terminology used in the field to specifictechnologies to the pros and cons of different implementations Discusses specific technologies that incorporate cryptographyin their design, such as authentication methods, wirelessencryption, e-commerce, and smart cards Based entirely on real-world issues and situations, thematerial provides instructions for already available technologiesthat readers can put to work immediately Expert author Chey Cobb is retired from the NRO, where she helda Top Secret security clearance, instructed employees of the CIAand NSA on computer security and helped develop the computersecurity policies used by all U.S. intelligence age', '21', 'http://books.google.com/books/content?id=b3pQDh7j5ogC&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=b3pQDh7j5ogC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 324, 3.5, 436, true, PARSEDATETIME('2004', 'yyyy'), 0, 1);INSERT INTO BOOK_TITLE_EDITIONS VALUES(1, 1);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(1, 1);
INSERT INTO EDITION_CONTENT VALUES(1, 0);
INSERT INTO EDITION_TAGS VALUES(1, 0);
INSERT INTO EDITION_TAGS VALUES(1, 1);
INSERT INTO EDITION_TAGS VALUES(1, 2);
INSERT INTO EDITION_TAGS VALUES(1, 3);
INSERT INTO BOOK_TITLE VALUES(2, 'Cryptography: A Very Short Introduction');
INSERT INTO EDITION VALUES(2, 41, 'This Very Short Introduction provides a clear and informative introduction to the science of codebreaking, and its explosive impact on modern society. Taking the reader through the actual processes of developing codes and deciphering them, the book explains what algorithms do, how they are used, the risks associated with using them, and why governments should be concerned. Written in a fluid and lively style to appeal to the non-mathematical reader, this makes for fascinating reading.', '19', 'http://books.google.com/books/content?id=HvR0DgAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=HvR0DgAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 142, 4.0, 295, true, PARSEDATETIME('2002', 'yyyy'), 1, 2);INSERT INTO BOOK_TITLE_EDITIONS VALUES(2, 2);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(2, 2);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(2, 3);
INSERT INTO EDITION_CONTENT VALUES(2, 0);
INSERT INTO EDITION_TAGS VALUES(2, 0);
INSERT INTO EDITION_TAGS VALUES(2, 1);
INSERT INTO EDITION_TAGS VALUES(2, 2);
INSERT INTO EDITION_TAGS VALUES(2, 3);
INSERT INTO BOOK_TITLE VALUES(3, 'Introduction to Cryptography');
INSERT INTO EDITION VALUES(3, 45, 'The opening section of this book covers key concepts of cryptography, from encryption and digital signatures to cryptographic protocols. Essential techniques are demonstrated in protocols for key exchange, user identification, electronic elections and digital cash. The second part addresses advanced topics, such as the bit security of one-way functions and computationally perfect pseudorandom bit generators. Examples of provably secure encryption and signature schemes and their security proofs are given. Though particular attention is given to the mathematical foundations, no special background in mathematics is presumed. The necessary algebra, number theory and probability theory are included in the appendix. Each chapter closes with a collection of exercises. The second edition presents new material, including a complete description of the AES, an extended section on cryptographic hash functions, a new section on random oracle proofs, and a new section on public-key encryption scheme', '18', 'http://books.google.com/books/content?id=Nnvhz_VqAS4C&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=Nnvhz_VqAS4C&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 367, 4.7, 572, true, PARSEDATETIME('2007', 'yyyy'), 2, 3);INSERT INTO BOOK_TITLE_EDITIONS VALUES(3, 3);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(3, 4);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(3, 5);
INSERT INTO EDITION_CONTENT VALUES(3, 0);
INSERT INTO EDITION_TAGS VALUES(3, 0);
INSERT INTO EDITION_TAGS VALUES(3, 1);
INSERT INTO EDITION_TAGS VALUES(3, 2);
INSERT INTO EDITION_TAGS VALUES(3, 3);
INSERT INTO BOOK_TITLE VALUES(4, 'Everyday Cryptography');
INSERT INTO EDITION VALUES(4, 24, 'Cryptography is a vital technology that underpins the security of information in computer networks. This book presents a comprehensive introduction to the role that cryptography plays in providing information security for everyday technologies such as the Internet, mobile phones, Wi-Fi networks, payment cards, Tor, and Bitcoin. This book is intended to be introductory, self-contained, and widely accessible. It is suitable as a first read on cryptography. Almost no prior knowledge of mathematics is required since the book deliberately avoids the details of the mathematics techniques underpinning cryptographic mechanisms. Instead our focus will be on what a normal user or practitioner of information security needs to know about cryptography in order to understand the design and use of everyday cryptographic applications. By focusing on the fundamental principles of modern cryptography rather than the technical details of current cryptographic technology, the main part this book is relati', '18', 'http://books.google.com/books/content?id=TS3VDgAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=TS3VDgAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 672, 3.9, 285, false, PARSEDATETIME('2017', 'yyyy'), 3, 4);INSERT INTO BOOK_TITLE_EDITIONS VALUES(4, 4);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(4, 6);
INSERT INTO EDITION_CONTENT VALUES(4, 0);
INSERT INTO EDITION_TAGS VALUES(4, 0);
INSERT INTO EDITION_TAGS VALUES(4, 1);
INSERT INTO EDITION_TAGS VALUES(4, 2);
INSERT INTO EDITION_TAGS VALUES(4, 3);
INSERT INTO BOOK_TITLE VALUES(5, 'Understanding Cryptography');
INSERT INTO EDITION VALUES(5, 33, 'Cryptography is now ubiquitous – moving beyond the traditional environments, such as government communications and banking systems, we see cryptographic techniques realized in Web browsers, e-mail programs, cell phones, manufacturing systems, embedded software, smart buildings, cars, and even medical implants. Today''s designers need a comprehensive understanding of applied cryptography. After an introduction to cryptography and data security, the authors explain the main techniques in modern cryptography, with chapters addressing stream ciphers, the Data Encryption Standard (DES) and 3DES, the Advanced Encryption Standard (AES), block ciphers, the RSA cryptosystem, public-key cryptosystems based on the discrete logarithm problem, elliptic-curve cryptography (ECC), digital signatures, hash functions, Message Authentication Codes (MACs), and methods for key establishment, including certificates and public-key infrastructure (PKI).', '22', 'http://books.google.com/books/content?id=f24wFELSzkoC&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=f24wFELSzkoC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 372, 4.1, 150, false, PARSEDATETIME('2009', 'yyyy'), 2, 5);INSERT INTO BOOK_TITLE_EDITIONS VALUES(5, 5);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(5, 7);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(5, 8);
INSERT INTO EDITION_CONTENT VALUES(5, 0);
INSERT INTO EDITION_TAGS VALUES(5, 0);
INSERT INTO EDITION_TAGS VALUES(5, 1);
INSERT INTO EDITION_TAGS VALUES(5, 2);
INSERT INTO EDITION_TAGS VALUES(5, 3);
INSERT INTO BOOK_TITLE VALUES(6, 'Theory of Cryptography');
INSERT INTO EDITION VALUES(6, 47, 'This book constitutes the refereed proceedings of the Second Theory of Cryptography Conference, TCC 2005, held in Cambridge, MA, USA in February 2005. The 32 revised full papers presented were carefully reviewed and selected from 84 submissions. The papers are organized in topical sections on hardness amplification and error correction, graphs and groups, simulation and secure computation, security of encryption, steganography and zero knowledge, secure computation, quantum cryptography and universal composability, cryptographic primitives and security, encryption and signatures, and information theoretic cryptography.', '20', 'http://books.google.com/books/content?id=6g5nI71vgiIC&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=6g5nI71vgiIC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 619, 4.7, 367, true, PARSEDATETIME('2005', 'yyyy'), 2, 6);INSERT INTO BOOK_TITLE_EDITIONS VALUES(6, 6);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(6, 9);
INSERT INTO EDITION_CONTENT VALUES(6, 1);
INSERT INTO EDITION_TAGS VALUES(6, 0);
INSERT INTO EDITION_TAGS VALUES(6, 1);
INSERT INTO EDITION_TAGS VALUES(6, 2);
INSERT INTO EDITION_TAGS VALUES(6, 3);
INSERT INTO BOOK_TITLE VALUES(7, 'Black Hat Python');
INSERT INTO EDITION VALUES(7, 32, 'In Black Hat Python, the latest from Justin Seitz (author of the best-selling Gray Hat Python), you’ll explore the darker side of Python’s capabilities—writing network sniffers, manipulating packets, infecting virtual machines, creating stealthy trojans, and more. You’ll learn how to: Create a trojan command-and-control using GitHubDetect sandboxing and automate com­mon malware tasks, like keylogging and screenshottingEscalate Windows privileges with creative process controlUse offensive memory forensics tricks to retrieve password hashes and inject shellcode into a virtual machineExtend the popular Burp Suite web-hacking toolAbuse Windows COM automation to perform a man-in-the-browser attackExfiltrate data from a network most sneakily Insider techniques and creative challenges throughout show you how to extend the hacks and how to write your own exploits. When it comes to offensive security, your ability to create powerful tools on the fly is indispensable.', '21', 'http://books.google.com/books/content?id=9MS9BQAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=9MS9BQAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 192, 4.3, 107, false, PARSEDATETIME('2014', 'yyyy'), 4, 7);INSERT INTO BOOK_TITLE_EDITIONS VALUES(7, 7);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(7, 10);
INSERT INTO EDITION_CONTENT VALUES(7, 0);
INSERT INTO EDITION_TAGS VALUES(7, 4);
INSERT INTO EDITION_TAGS VALUES(7, 5);
INSERT INTO EDITION_TAGS VALUES(7, 2);
INSERT INTO BOOK_TITLE VALUES(8, 'Python in a Nutshell');
INSERT INTO EDITION VALUES(8, 55, 'Demonstrates the programming language''s strength as a Web development tool, covering syntax, data types, built-ins, the Python standard module library, and real world examples.', '18', 'http://books.google.com/books/content?id=pjqbAgAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=pjqbAgAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 695, 2.0, 79, true, PARSEDATETIME('2006', 'yyyy'), 5, 8);INSERT INTO BOOK_TITLE_EDITIONS VALUES(8, 8);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(8, 11);
INSERT INTO EDITION_CONTENT VALUES(8, 0);
INSERT INTO EDITION_TAGS VALUES(8, 4);
INSERT INTO EDITION_TAGS VALUES(8, 5);
INSERT INTO EDITION_TAGS VALUES(8, 2);
INSERT INTO BOOK_TITLE VALUES(9, 'Automate the Boring Stuff with Python');
INSERT INTO EDITION VALUES(9, 22, 'If you’ve ever spent hours renaming files or updating hundreds of spreadsheet cells, you know how tedious tasks like these can be. But what if you could have your computer do them for you? In Automate the Boring Stuff with Python, you’ll learn how to use Python to write programs that do in minutes what would take you hours to do by hand—no prior programming experience required. Once you’ve mastered the basics of programming, you’ll create Python programs that effortlessly perform useful and impressive feats of automation to: Search for text in a file or across multiple filesCreate, update, move, and rename files and foldersSearch the Web and download online contentUpdate and format data in Excel spreadsheets of any sizeSplit, merge, watermark, and encrypt PDFsSend reminder emails and text notificationsFill out online forms Step-by-step instructions walk you through each program, and practice projects at the end of each chapter challenge you to improve those programs and use your newfou', '20', 'http://books.google.com/books/content?id=UEu0CAAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=UEu0CAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 504, 3.9, 416, true, PARSEDATETIME('2015', 'yyyy'), 4, 9);INSERT INTO BOOK_TITLE_EDITIONS VALUES(9, 9);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(9, 12);
INSERT INTO EDITION_CONTENT VALUES(9, 0);
INSERT INTO EDITION_TAGS VALUES(9, 4);
INSERT INTO EDITION_TAGS VALUES(9, 5);
INSERT INTO EDITION_TAGS VALUES(9, 2);
INSERT INTO BOOK_TITLE VALUES(10, 'Python Playground');
INSERT INTO EDITION VALUES(10, 51, 'Python is a powerful programming language that’s easy to learn and fun to play with. But once you’ve gotten a handle on the basics, what do you do next? Python Playground is a collection of imaginative programming projects that will inspire you to use Python to make art and music, build simulations of real-world phenomena, and interact with hardware like the Arduino and Raspberry Pi. You’ll learn to use common Python tools and libraries like numpy, matplotlib, and pygame to do things like: *Generate Spirograph-like patterns using parametric equations and the turtle module *Create music on your computer by simulating frequency overtones *Translate graphical images into ASCII art *Write an autostereogram program that produces 3D images hidden beneath random patterns *Make realistic animations with OpenGL shaders by exploring particle systems, transparency, and billboarding techniques *Construct 3D visualizations using data from CT and MRI scans *Build a laser show that responds to music ', '18', 'http://books.google.com/books/content?id=YRHSCgAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=YRHSCgAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 352, 3.8, 85, false, PARSEDATETIME('2015', 'yyyy'), 4, 10);INSERT INTO BOOK_TITLE_EDITIONS VALUES(10, 10);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(10, 13);
INSERT INTO EDITION_CONTENT VALUES(10, 0);
INSERT INTO EDITION_TAGS VALUES(10, 4);
INSERT INTO EDITION_TAGS VALUES(10, 5);
INSERT INTO EDITION_TAGS VALUES(10, 2);
INSERT INTO BOOK_TITLE VALUES(11, 'Python Essential Reference');
INSERT INTO EDITION VALUES(11, 49, 'Presents a guide to the features and library modules of the Python programming language.', '18', 'http://books.google.com/books/content?id=Chr1NDlUcI8C&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=Chr1NDlUcI8C&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 717, 1.3, 101, true, PARSEDATETIME('2009', 'yyyy'), 6, 11);INSERT INTO BOOK_TITLE_EDITIONS VALUES(11, 11);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(11, 14);
INSERT INTO EDITION_CONTENT VALUES(11, 0);
INSERT INTO EDITION_TAGS VALUES(11, 4);
INSERT INTO EDITION_TAGS VALUES(11, 5);
INSERT INTO EDITION_TAGS VALUES(11, 2);
INSERT INTO BOOK_TITLE VALUES(12, 'Python Programming');
INSERT INTO EDITION VALUES(12, 55, 'This book is suitable for use in a university-level first course in computing (CS1), as well as the increasingly popular course known as CS0. It is difficult for many students to master basic concepts in computer science and programming. A large portion of the confusion can be blamed on the complexity of the tools and materials that are traditionally used to teach CS1 and CS2. This textbook was written with a single overarching goal: to present the core concepts of computer science as simply as possible without being simplistic.', '20', 'http://books.google.com/books/content?id=aJQILlLxRmAC&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=aJQILlLxRmAC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 517, 2.3, 229, true, PARSEDATETIME('2004', 'yyyy'), 7, 12);INSERT INTO BOOK_TITLE_EDITIONS VALUES(12, 12);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(12, 15);
INSERT INTO EDITION_CONTENT VALUES(12, 0);
INSERT INTO EDITION_TAGS VALUES(12, 4);
INSERT INTO EDITION_TAGS VALUES(12, 5);
INSERT INTO EDITION_TAGS VALUES(12, 2);
INSERT INTO BOOK_TITLE VALUES(13, 'Learning Python with Raspberry Pi');
INSERT INTO EDITION VALUES(13, 18, 'Explains how to leverage the revolutionary Raspberry Pi computer in order to learn the versatile Python programming language. Original.', '19', 'http://books.google.com/books/content?id=BP_WAgAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=BP_WAgAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 286, 2.6, 105, true, PARSEDATETIME('2014', 'yyyy'), 0, 13);INSERT INTO BOOK_TITLE_EDITIONS VALUES(13, 13);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(13, 16);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(13, 17);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(13, 18);
INSERT INTO EDITION_CONTENT VALUES(13, 0);
INSERT INTO EDITION_TAGS VALUES(13, 4);
INSERT INTO EDITION_TAGS VALUES(13, 5);
INSERT INTO EDITION_TAGS VALUES(13, 2);
INSERT INTO BOOK_TITLE VALUES(14, 'The C++ Standard Library');
INSERT INTO EDITION VALUES(14, 26, 'A proven best-seller, updated for the new standard: still the most practical C++ Standard Library tutorial and most complete reference * *Thoroughly documents each library component incorporated in the brand-new C++ standard. *Clearly explains complex concepts, and presents the practical detail programmers need to use the Standard Library effectively. *Contains many examples of working code, all available for download at an accompanying website. The C++ Standard Library, 2/e, doesn''t just provide comprehensive documentation of every library component associated with the newest C++ standard: it also offers clearly-written explanations of complex concepts, reviews practical programming details needed for effective use, and presents many useful examples of working code - all of them available for download. Fully updated to reflect the newest elements of the C++ Standard Library incorporated into the full ANSI/ISO C++ language standard, this book examines containers, iterators, function o', '18', 'http://books.google.com/books/content?id=gUhE8po4jgAC&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=gUhE8po4jgAC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 1099, 2.6, 116, true, PARSEDATETIME('2012', 'yyyy'), 6, 14);INSERT INTO BOOK_TITLE_EDITIONS VALUES(14, 14);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(14, 19);
INSERT INTO EDITION_CONTENT VALUES(14, 0);
INSERT INTO EDITION_TAGS VALUES(14, 4);
INSERT INTO EDITION_TAGS VALUES(14, 6);
INSERT INTO EDITION_TAGS VALUES(14, 2);
INSERT INTO BOOK_TITLE VALUES(15, 'Practical C++ Programming');
INSERT INTO EDITION VALUES(15, 12, 'Teaches the programming language, covering topics including syntax, coding standards, object classes, templates, debugging, and the C++ preprocessor.', '18', 'http://books.google.com/books/content?id=pXDzdJ_1E3oC&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=pXDzdJ_1E3oC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 549, 2.6, 361, false, PARSEDATETIME('2003', 'yyyy'), 5, 15);INSERT INTO BOOK_TITLE_EDITIONS VALUES(15, 15);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(15, 20);
INSERT INTO EDITION_CONTENT VALUES(15, 0);
INSERT INTO EDITION_TAGS VALUES(15, 4);
INSERT INTO EDITION_TAGS VALUES(15, 6);
INSERT INTO EDITION_TAGS VALUES(15, 2);
INSERT INTO BOOK_TITLE VALUES(16, 'Accelerated C++');
INSERT INTO EDITION VALUES(16, 10, 'Takes a practical approach to solving problems using C++. This book describes real problems and solutions, not just language features. It covers the language and standard library together.', '20', 'http://books.google.com/books/content?id=OaVQAAAAMAAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=OaVQAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 336, 4.1, 552, true, PARSEDATETIME('2000', 'yyyy'), 6, 16);INSERT INTO BOOK_TITLE_EDITIONS VALUES(16, 16);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(16, 21);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(16, 22);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(16, 23);
INSERT INTO EDITION_CONTENT VALUES(16, 0);
INSERT INTO EDITION_TAGS VALUES(16, 4);
INSERT INTO EDITION_TAGS VALUES(16, 6);
INSERT INTO EDITION_TAGS VALUES(16, 2);
INSERT INTO BOOK_TITLE VALUES(17, 'C++ For Dummies');
INSERT INTO EDITION VALUES(17, 29, 'The best-selling C++ For Dummies book makes C++ easier! C++ For Dummies, 7th Edition is the best-selling C++ guide on the market, fully revised for the 2014 update. With over 60% new content, this updated guide reflects the new standards, and includes a new Big Data focus that highlights the use of C++ among popular Big Data software solutions. The book provides step-by-step instruction from the ground up, helping beginners become programmers and allowing intermediate programmers to sharpen their skills. The companion website provides all code mentioned in the text, an updated GNU_C++, the new C++ compiler, and other applications. By the end of the first chapter, you will have programmed your first C++ application! As one of the most commonly used programming languages, C++ is a must-have skill for programmers who wish to remain versatile and marketable. C++ For Dummies, 7th Edition provides clear, concise, expert instruction, which is organized for easy navigation and designed for han', '18', 'http://books.google.com/books/content?id=nKycAwAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=nKycAwAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 480, 2.6, 505, true, PARSEDATETIME('2014', 'yyyy'), 0, 17);INSERT INTO BOOK_TITLE_EDITIONS VALUES(17, 17);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(17, 24);
INSERT INTO EDITION_CONTENT VALUES(17, 0);
INSERT INTO EDITION_TAGS VALUES(17, 4);
INSERT INTO EDITION_TAGS VALUES(17, 6);
INSERT INTO EDITION_TAGS VALUES(17, 2);
INSERT INTO BOOK_TITLE VALUES(18, 'Professional C++');
INSERT INTO EDITION VALUES(18, 30, 'Get up to date quickly on the new changes coming with C++17 Professional C++ is the advanced manual for C++ programming. Designed to help experienced developers get more out of the latest release, this book skims over the basics and dives right in to exploiting the full capabilities of C++17. Each feature is explained by example, each including actual code snippets that you can plug into your own applications. Case studies include extensive, working code that has been tested on Windows and Linux, and the author''s expert tips, tricks, and workarounds can dramatically enhance your workflow. Even many experienced developers have never fully explored the boundaries of the language''s capabilities; this book reveals the advanced features you never knew about, and drills down to show you how to turn these features into real-world solutions. The C++17 release includes changes that impact the way you work with C++; this new fourth edition covers them all, including nested namespaces, structur', '18', 'http://books.google.com/books/content?id=OY9ODwAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=OY9ODwAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 1184, 2.2, 383, false, PARSEDATETIME('2018', 'yyyy'), 0, 18);INSERT INTO BOOK_TITLE_EDITIONS VALUES(18, 18);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(18, 25);
INSERT INTO EDITION_CONTENT VALUES(18, 0);
INSERT INTO EDITION_TAGS VALUES(18, 4);
INSERT INTO EDITION_TAGS VALUES(18, 6);
INSERT INTO EDITION_TAGS VALUES(18, 2);
INSERT INTO BOOK_TITLE VALUES(19, 'Large-scale C++ Software Design');
INSERT INTO EDITION VALUES(19, 42, 'The topic is of prime importance to software professionals involved in large development efforts such as databases, operating systems, compilers, and frameworks. This volume explains the process of decomposing large systems into physical (not inheritance) hierarchies of small, manageable components. Concepts and techniques are illustrated with "war stories" from the development firm, Mentor Graphics, as well as with a large-scale example comprising some 12,000 lines of code. Annotation copyright by Book News, Inc., Portland, OR', '21', 'http://books.google.com/books/content?id=AuMpAQAAMAAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=AuMpAQAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 846, 3.0, 326, true, PARSEDATETIME('1996', 'yyyy'), 6, 19);INSERT INTO BOOK_TITLE_EDITIONS VALUES(19, 19);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(19, 26);
INSERT INTO EDITION_CONTENT VALUES(19, 0);
INSERT INTO EDITION_TAGS VALUES(19, 4);
INSERT INTO EDITION_TAGS VALUES(19, 6);
INSERT INTO EDITION_TAGS VALUES(19, 2);
INSERT INTO BOOK_TITLE VALUES(20, 'Statistical Computing in C++ and R');
INSERT INTO EDITION VALUES(20, 38, 'With the advancement of statistical methodology inextricably linked to the use of computers, new methodological ideas must be translated into usable code and then numerically evaluated relative to competing procedures. In response to this, Statistical Computing in C++ and R concentrates on the writing of code rather than the development and study of numerical algorithms per se. The book discusses code development in C++ and R and the use of these symbiotic languages in unison. It emphasizes that each offers distinct features that, when used in tandem, can take code writing beyond what can be obtained from either language alone. The text begins with some basics of object-oriented languages, followed by a "boot-camp" on the use of C++ and R. The authors then discuss code development for the solution of specific computational problems that are relevant to statistics including optimization, numerical linear algebra, and random number generation.', '22', 'http://books.google.com/books/content?id=CmZRui57cWkC&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=CmZRui57cWkC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 556, 4.7, 526, false, PARSEDATETIME('2011', 'yyyy'), 8, 20);INSERT INTO BOOK_TITLE_EDITIONS VALUES(20, 20);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(20, 27);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(20, 28);
INSERT INTO EDITION_CONTENT VALUES(20, 2);
INSERT INTO EDITION_TAGS VALUES(20, 4);
INSERT INTO EDITION_TAGS VALUES(20, 6);
INSERT INTO EDITION_TAGS VALUES(20, 2);
INSERT INTO BOOK_TITLE VALUES(21, 'C++ In a Nutshell');
INSERT INTO EDITION VALUES(21, 50, 'C++ is a powerful, highly flexible, and adaptable programming language that allows software engineers to organize and process information quickly and effectively. This is a complete reference to C++.', '20', 'http://books.google.com/books/content?id=Y6NVAAAAMAAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=Y6NVAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 791, 2.0, 64, true, PARSEDATETIME('2003', 'yyyy'), 9, 21);INSERT INTO BOOK_TITLE_EDITIONS VALUES(21, 21);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(21, 29);
INSERT INTO EDITION_CONTENT VALUES(21, 0);
INSERT INTO EDITION_TAGS VALUES(21, 4);
INSERT INTO EDITION_TAGS VALUES(21, 6);
INSERT INTO EDITION_TAGS VALUES(21, 2);
INSERT INTO BOOK_TITLE VALUES(22, 'C++ for Everyone');
INSERT INTO EDITION VALUES(22, 11, 'C++ for Everyone 2nd Edition appeals to readers by offering concise, thorough, and easily palatable coverage of the essential C++ concepts that provides a solid foundation of programming. New supplemental engineering examples will appeal directly to the larger market of engineers. This text incorporates a substantial number of new self-check questions and simple programming exercises that reinforce the concepts. A greater emphasis on problem-solving throughout the book will help readers actively apply the core concepts and will benefit all readers.', '21', 'http://books.google.com/books/content?id=4GvgCAAAQBAJ&printsec=frontcover&img=1&source=gbs_api', 'http://books.google.com/books/content?id=4GvgCAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'un', 560, 2.3, 554, true, PARSEDATETIME('2010', 'yyyy'), 0, 22);INSERT INTO BOOK_TITLE_EDITIONS VALUES(22, 22);
INSERT INTO EDITION_CONTRIBUTIONS VALUES(22, 30);
INSERT INTO EDITION_CONTENT VALUES(22, 0);
INSERT INTO EDITION_TAGS VALUES(22, 4);
INSERT INTO EDITION_TAGS VALUES(22, 6);
INSERT INTO EDITION_TAGS VALUES(22, 2);
